// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.antti.entities;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Cubicle_Roo_Configurable {
    
    declare @type: Cubicle: @Configurable;
    
}
